### ISSUE TITLE
put quotes around login parameters

### ISSUE THREAD

**Issue by smithjd** [smithjd/sqlpetr#46]
Currently the default on the connection tab is:

`user, password, dbname,`

To insert your parameters, you need to enter a value and the quotes.  If the default had quotes as follows it would be easier to use:

`"user", "password", "dbname",`

In Rstudio when you click on something inside quotes, it lets you edit just what's in the quotes.  Without quotes you have to enter the parameters and the quotes, which can be fiddly.

**Comment by znmeb** [comment]
I'm going to set defaults for those - it'll be syntactically correct that way and easier to read.

**Comment by znmeb** [comment]
in the branch - closing
